config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, except: [:new]
  resources :users, only: [:index, :show, :edit, :update]

  get "/home/about" => "homes#about", as: "about"
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_one_attached :profile_image

def get_profile_image(width, height)
unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
end
      profile_image.variant(resize_to_limit: [width, height]).processed
end

  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum:50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
	  user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create

    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:success] = 'Book was successfully updated.'
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
    @books = Book.all
  end

  def show
    @book = Book.new
    @users = User.all
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:success] = 'User was successfully updated.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<p><%= image_tag current_user.get_profile_image(100, 100) %></p>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th><th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody></table>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>

  <h2 class="mt-3">New book</h2>
<!-- form_with部分 -->
  <%= form_with model: book do |f| %>
  <div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
  </div>
<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class: "form-control book_body", id: "book_opinion" %>
  </div>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Option</h4>
  <%= f.text_area :body %><br>
  <%= f.submit "Update Book", class: "btn btn-success" %><br>
  <%= link_to "Show", book_path(@book) %>|
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
<%= render 'list', user:@user ,book:@book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<thead>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
 </tr>
</thead>
<% @books.each do |book| %>
<tbody>
  <tr>
    <td><%= link_to user_path(book.user.id) do%><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
    <td>
      <span><%= link_to book.title, book_path(book.id) %></span>
    </td>
    <td>
      <span><%= book.body %></span>
    </td>
    <td></td>
  </tr>
</tbody>

<% end %>
  </table>
  </div>
   </div>
  </div>

app/views/books/show.html.erb
<%= flash[:success] %>

<div class="container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
<%= render 'list', user:@book.user ,book:@new_book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
<table class="table table-hover table-inverse">

<thead>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
 </tr>
</thead>
<tbody>
  <tr>
    <td><%= link_to user_path(@book.user.id) do%><%= image_tag @book.user.get_profile_image(100,100) %><br><%= @book.user.name %><% end %></td>
    <td>
      <span><%= link_to @book.title, book_path(@book.id) %></span>
    </td>
    <td>
      <span><%= @book.body %></span>
    </td>
    <% if @book.user == current_user %>
     <td><%= link_to "Edit",edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger" %></td>
    <% end %>
    <td></td>
  </tr>
</tbody>
  </table>
  </div>
   </div>
  </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>,
      </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapperclass col-10 mx-auto">
        <div class="row">
          <%= link_to("Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in") %>
        </div>
        <div class="row">
          <%= link_to("Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><script src="https://kit.fontawesome.com/c946fd5e76.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to("Bookers", root_path, class: "navbar-brand") %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li><%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
         </li>
          <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
         </li>
         <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
         </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
            <% else %>
        <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
         </li>
          <li>
            <%= link_to "About", about_path, class: "fas fa-link nav-link text-light" %>
         </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
     </li>
          <li>
            <%= link_to "Log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>

  <main><p id="notice"><%= notice %></p><%= yield %></main>
  <footer>
    <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :image %><br>
  <%= f.file_field :profile_image, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :introduction %><br>
  <%= f.text_field :introduction, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.submit "Update User", class: "btn btn-secondary" %>
<% end %>

<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
<%= render 'books/list', user:@user ,book:@book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
<table class="table table-hover table-inverse">

<thead>
 <tr>
  <th></th>
  <th>image</th>
  <th>name</th>
  <th colspan="3"></th>
 </tr>
</thead>
<% @users.each do |user| %>
<tbody>
  <tr>
    <td><%= image_tag user.get_profile_image(100,100) %></td>
     <td>
       <%= user.name %>
     </td>
    <td>
      <span><%= link_to "Show", user_path(user.id) %></span>
    </td>
  </tr>
</tbody>

<% end %>
  </table>
  </div>
   </div>
  </div>

app/views/users/show.html.erb
<%= flash[:success] %>

<div class="container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
<%= render 'books/list', user:@user ,book:@book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">

<thead>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
 </tr>
</thead>
<% @books.each do |book| %>
<tbody>
  <tr>
    <td><%= link_to user_path(book.user.id) do%><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
    <td>
      <span><%= link_to book.title, book_path(book.id) %></span>
    </td>
    <td>
      <span><%= book.body %></span>
    </td>
    <td></td>
  </tr>
</tbody>

<% end %>
  </table>
  </div>
   </div>
  </div>